name: saltstack-nfs-formula
source: https://github.com/bechtoldt/saltstack-nfs-formula
summary: SaltStack Formula to set up and configure NFS, the network file system
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - manage rpcbind service
